# Generated by Django 3.0.8 on 2020-07-27 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Company', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='company')),
                ('company_name', models.CharField(max_length=250, verbose_name='Company Name')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('city_location', models.CharField(max_length=150, verbose_name='City')),
                ('province_location', models.CharField(max_length=150, verbose_name='Province')),
                ('country_location', models.CharField(max_length=150, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Comapany',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
