# Generated by Django 3.0.8 on 2020-08-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='table',
        ),
        migrations.AddField(
            model_name='reservation',
            name='table_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Table Id'),
        ),
    ]
