# Generated by Django 3.0.8 on 2020-08-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
