# Generated by Django 3.0.8 on 2020-07-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20200722_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='Phone Number'),
        ),
    ]
