# Generated by Django 3.0.8 on 2020-08-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20200801_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_type',
            field=models.CharField(choices=[('food', 'Food'), ('drink', 'Drink'), ('interior', 'Interior'), ('exterior', 'Exterior')], max_length=50, verbose_name='type'),
        ),
    ]
