# Generated by Django 3.0.8 on 2020-08-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20200801_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Photo Url'),
        ),
    ]
