# Generated by Django 3.0.8 on 2020-07-22 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Customer', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='customer'),
        ),
    ]
