# Generated by Django 3.0.8 on 2020-07-24 08:59

import account.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200722_1216'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account.managers.UserManager()),
            ],
        ),
    ]
